/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoveRecord: typeof import('./src/components/LoveRecord.vue')['default']
    NutCalendar: typeof import('nutui-uniapp/components/calendar/calendar.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutRadio: typeof import('nutui-uniapp/components/radio/radio.vue')['default']
    NutRadioGroup: typeof import('nutui-uniapp/components/radiogroup/radiogroup.vue')['default']
    PeriodRecord: typeof import('./src/components/PeriodRecord.vue')['default']
    RecordItem: typeof import('./src/components/RecordItem.vue')['default']
    RecordSection: typeof import('./src/components/RecordSection.vue')['default']
  }
}
